services:
  postgres:
    image: postgres:18.4-alpine3.23
    ports: 
     - "5432:5432"
    env_file:
      - ".env"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]