// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: shortener.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNewCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewCodeReq) Reset() {
	*x = CreateNewCodeReq{}
	mi := &file_shortener_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewCodeReq) ProtoMessage() {}

func (x *CreateNewCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewCodeReq.ProtoReflect.Descriptor instead.
func (*CreateNewCodeReq) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNewCodeReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreateNewCodeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewCodeResp) Reset() {
	*x = CreateNewCodeResp{}
	mi := &file_shortener_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewCodeResp) ProtoMessage() {}

func (x *CreateNewCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewCodeResp.ProtoReflect.Descriptor instead.
func (*CreateNewCodeResp) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNewCodeResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateNewCodeResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetOriginalUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalUrlReq) Reset() {
	*x = GetOriginalUrlReq{}
	mi := &file_shortener_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalUrlReq) ProtoMessage() {}

func (x *GetOriginalUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalUrlReq.ProtoReflect.Descriptor instead.
func (*GetOriginalUrlReq) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{2}
}

func (x *GetOriginalUrlReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetOriginalUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOriginalUrlResp) Reset() {
	*x = GetOriginalUrlResp{}
	mi := &file_shortener_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOriginalUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOriginalUrlResp) ProtoMessage() {}

func (x *GetOriginalUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_shortener_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOriginalUrlResp.ProtoReflect.Descriptor instead.
func (*GetOriginalUrlResp) Descriptor() ([]byte, []int) {
	return file_shortener_proto_rawDescGZIP(), []int{3}
}

func (x *GetOriginalUrlResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_shortener_proto protoreflect.FileDescriptor

const file_shortener_proto_rawDesc = "" +
	"\n" +
	"\x0fshortener.proto\x12\fgrpc_api_gen\"$\n" +
	"\x10CreateNewCodeReq\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"9\n" +
	"\x11CreateNewCodeResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"'\n" +
	"\x11GetOriginalUrlReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"&\n" +
	"\x12GetOriginalUrlResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xb2\x01\n" +
	"\tShortener\x12P\n" +
	"\rCreateNewCode\x12\x1e.grpc_api_gen.CreateNewCodeReq\x1a\x1f.grpc_api_gen.CreateNewCodeResp\x12S\n" +
	"\x0eGetOriginalUrl\x12\x1f.grpc_api_gen.GetOriginalUrlReq\x1a .grpc_api_gen.GetOriginalUrlRespB\bZ\x06proto/b\x06proto3"

var (
	file_shortener_proto_rawDescOnce sync.Once
	file_shortener_proto_rawDescData []byte
)

func file_shortener_proto_rawDescGZIP() []byte {
	file_shortener_proto_rawDescOnce.Do(func() {
		file_shortener_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortener_proto_rawDesc), len(file_shortener_proto_rawDesc)))
	})
	return file_shortener_proto_rawDescData
}

var file_shortener_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shortener_proto_goTypes = []any{
	(*CreateNewCodeReq)(nil),   // 0: grpc_api_gen.CreateNewCodeReq
	(*CreateNewCodeResp)(nil),  // 1: grpc_api_gen.CreateNewCodeResp
	(*GetOriginalUrlReq)(nil),  // 2: grpc_api_gen.GetOriginalUrlReq
	(*GetOriginalUrlResp)(nil), // 3: grpc_api_gen.GetOriginalUrlResp
}
var file_shortener_proto_depIdxs = []int32{
	0, // 0: grpc_api_gen.Shortener.CreateNewCode:input_type -> grpc_api_gen.CreateNewCodeReq
	2, // 1: grpc_api_gen.Shortener.GetOriginalUrl:input_type -> grpc_api_gen.GetOriginalUrlReq
	1, // 2: grpc_api_gen.Shortener.CreateNewCode:output_type -> grpc_api_gen.CreateNewCodeResp
	3, // 3: grpc_api_gen.Shortener.GetOriginalUrl:output_type -> grpc_api_gen.GetOriginalUrlResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shortener_proto_init() }
func file_shortener_proto_init() {
	if File_shortener_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortener_proto_rawDesc), len(file_shortener_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortener_proto_goTypes,
		DependencyIndexes: file_shortener_proto_depIdxs,
		MessageInfos:      file_shortener_proto_msgTypes,
	}.Build()
	File_shortener_proto = out.File
	file_shortener_proto_goTypes = nil
	file_shortener_proto_depIdxs = nil
}
