CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE urls
ADD COLUMN user_id INTEGER DEFAULT 0 REFERENCES users(id) ON DELETE CASCADE; 
ALTER TABLE urls
ADD COLUMN clicks INTEGER DEFAULT 0; 